spring.application.name=StringBatchPractice
spring.datasource.url=jdbc:postgresql://localhost:5432/posgrePractice
spring.datasource.username=postgres
spring.datasource.password=1213
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.batch.jdbc.initialize-schema=always
#spring.batch.job.names=hello-job bizDate=20260129
spring.batch.job.names=CompositeProcessor-job
